version: "3.7"

services:
  app:
    build:
      context: .
    container_name: abt-epts  
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=abt-epts
      - DB_USER=abt-epts
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: abt-eptsdb
    environment:
      - POSTGRES_DB=abt-epts
      - POSTGRES_USER=abt-epts
      - POSTGRES_PASSWORD=supersecretpassword
