# Generated by Django 3.2.4 on 2021-06-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('genero', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateTimeField()),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_escolaridade', models.CharField(blank=True, max_length=100, null=True)),
                ('confidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.confidente')),
            ],
        ),
    ]
